### ISSUE TITLE
Sharenite Synchronization Failed.

### ISSUE THREAD

**Issue by SearchingForGryphons** [sharenite/playnite-sharenite#15]
Trying to sync the add-on to the site gives me this issue;

Sharenite synchronization failed.
Problem reading cookies from disk: System.IO.FileNotFoundException

From what I can figure out System.IO.FileNotFoundException typically means there is a missing file, but there is no indication of which file. Any help would be highly appreciated, thanks.

**Comment by XenorPLxx** [comment]
@SearchingForGryphons are you authenticated into Sharenite like on the screenshot?
![image](https://user-images.githubusercontent.com/6712823/210216753-e5511998-f690-4643-9966-1735e85d405d.png)

If yes, and that doesn't help, then go to the 'Data folder' and delete all add-on files to start fresh.
![image](https://user-images.githubusercontent.com/6712823/210216825-0a50929f-53f6-4f0b-a71d-8907094fca29.png)

**Comment by SearchingForGryphons** [comment]
Not actually linking seems to have been the problem :( oops,  feel kind of dumb haha, tysm for the help :)
