### ISSUE TITLE
Sharenite disables QuickSearch

### ISSUE THREAD

**Issue by tynansdtm** [sharenite/playnite-sharenite#2]
When Sharenite is enabled, it blocks the keyboard shortcuts for [QuickSearch](https://github.com/felixkmh/QuickSearch-for-Playnite). It even blocks the global shortcut that works even when Playnite is minimized. However I know QuickSearch is still working, because I can put a search field widget on my Start Page and search my games that way.

**Comment by XenorPLxx** [comment]
I can reproduce, will check it out.

**Comment by XenorPLxx** [comment]
We've discussed the issue and a proper way to fix it would be on QuickSearch side, here's an issue report to follow:
@tynansdtm https://github.com/felixkmh/QuickSearch-for-Playnite/issues/61
